#
#  Copyright (C) 2011  Vladimir Rutsky <altsysrq@gmail.com>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os.path
import itertools

import SCons.Util

Import('global_env')
env = global_env.Clone()

sources = ['chi_square.cpp']

main = env.Program(target="main",
    source=['main.cpp'] + sources)

Default(main)

test_env = env.Clone()
test_env.AppendUnique(
    #LIBPATH=['#boost-lib'],
    LIBS=['boost_unit_test_framework'])
test_sources = (
    [test_env.Object('test_' + cpp.replace('.cpp', ''), cpp) 
        for cpp in sources] +
    ['chi_square_test.cpp']
    )
test = test_env.Program(target="test",
    source=['unit_testing.cpp'] + test_sources)

run_tests = Command(
    ".passed",
    test,
    "{tests} && date -R > $TARGET".\
        format(tests=str(test[0].abspath))) 

Default(run_tests)

# vim: set filetype=python ts=4 sw=4 et:
