#  This program is part of risk calculation suite.
#
#  Copyright (C) 2011  Vladimir Rutsky <altsysrq@gmail.com>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os

Import('env')

sources = \
    Glob("*.py", strings=True) + \
    Glob("forms/*.ui", strings=True) + \
    Glob("i18n/*.ts", strings=True)

build_cx_freeze = env.Command("build_cx-freeze", sources,
    "python setup_cx-freeze.py build",
    chdir=True)
Clean(build_cx_freeze, ['build'])

lupdate = env.Command("lupdate", 
    ["risk_calculation.pro"], # TODO
    "pylupdate4 risk_calculation.pro",
    chdir=True)

Default()

# vim: set filetype=python ts=4 sw=4 et:
