#
#  Copyright (C) 2011  Vladimir Rutsky <altsysrq@gmail.com>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os

global_env = Environment()
Export('global_env')

global_env.AppendUnique(LIBS=['m'])

SConscript(os.path.join("report", "SConscript"), 
    variant_dir=os.path.join("build", "report"))
#SConscript(os.path.join("report", "SConscript"))

SConscript(os.path.join("src", "SConscript"), 
    variant_dir=os.path.join("build", "src"))

# vim: set filetype=python ts=4 sw=4 et:
